# Nedbank REST API issues

* `FicaMe.yml`

[options="header"]
|===
|`API` path |`HTTP` method |Issue description

|`/id-verification/v2/parties/{partyId}/IDOCRExtractions`
|`POST`
a|

* According to swagger docs it can get customer details from identity document image (passport, ID Card or ID Book) how should we match this to Smart ID and Green Book ID
* According to source code it can only scan `IdCard` or `IdBook` how should we match this to Smart ID and Green Book ID
* `partyId` seems to be a resource identifier. According to the `API` it must be provided by the client but it is not clear how it should be obtained.

|`/id-verification/v2/parties/{partyId}/facialRecognitionProfiles`
|`POST`
a|

* Same issue as for `OCR` endpoint - `partyId` seems to be a resource identifier provided by the client, but it is unclear how it should be obtained.

|`/address-verification/v2/parties/address-document`
|`POST`
a|

* Service requires following request:
+
[source,json]
----
{
  "partyId": "string",
  "document": "string",
  "documentType": "string"
}
----
+
** How `partyId` should be obtained? It's the common issue (see `id-verification` endpoints issues).
** `document` value is encrypted and sent to the 3rd party `API`. What values are expected within `document`?
** What values are expected within `documentType`?
* Endpoint path declared within documentation is different than defined by the service
** Path declared by the documentation: `/address-verification/v2/parties/address-document`
** Path defined by the service: `/address-verification/v2/parties/match-address-document`
* Swagger documentation claims that the service returns customer address obtained from the vendor:
+
____
Mines for the customer address from the vendor
____
+
According to source code customer address is not being retrieved and service response contains some unclear values instead (either `SUCCESS` or `FAILURE`).
* According to source code service response can contain some additional fields not mentioned by the documentation - `firstName` and `documentIssueDate`. Example responses:
+
[source,json]
----
{
    "firstName": "(...)",
    "responseMessage": "SUCCESS",
    "documentIssueDate": "(...)"
}
----
+
[source,json]
----
{
    "responseMessage": "FAILURE",
    "documentIssueDate": "(...)"
}
----
* External `API` is used to `OCR` document provided by the client. Looks like it's response does not contain required address details.

|===
